package lcmessage

const (
	USER_SYSTEM_MESSAGE = 1000
	USER_WOLAI_SUPPORT  = 1001
	USER_TRADE_RECORD   = 1002
	USER_WOLAI_TEAM     = 1003
	USER_WOLAI_TUTOR    = 2001

	LC_MSG_TEXT       = -1
	LC_MSG_SYSTEM     = 1
	LC_MSG_IMAGE      = 2
	LC_MSG_VOICE      = 3
	LC_MSG_DISCOVER   = 4
	LC_MSG_ORDER      = 5
	LC_MSG_SESSION    = 6
	LC_MSG_WHITEBOARD = 7
	LC_MSG_TRADE      = 8
	LC_MSG_AD         = 9

	LC_DISCOVER_TYPE_COMMENT = "0"
	LC_DISCOVER_TYPE_LIKE    = "1"
)
